#!/bin/bash

echo "🚨 URGENTE: Execute o SQL no Supabase Dashboard"
echo ""
echo "❌ Erro encontrado: Colunas 'manager_id' não existem na tabela 'videos'"
echo ""
echo "🔧 SOLUÇÃO RÁPIDA:"
echo "1. Abra: https://supabase.com/dashboard"
echo "2. Entre no seu projeto"
echo "3. Vá em 'SQL Editor'"
echo "4. Copie e execute o SQL abaixo:"
echo ""
echo "================================================"
echo "-- SQL PARA EXECUTAR NO SUPABASE:"
echo ""
echo "-- Adicionar colunas necessárias"
echo "ALTER TABLE public.videos"
echo "ADD COLUMN IF NOT EXISTS created_by_type VARCHAR DEFAULT 'system',"
echo "ADD COLUMN IF NOT EXISTS created_by_id UUID,"
echo "ADD COLUMN IF NOT EXISTS manager_id UUID REFERENCES public.managers(id),"
echo "ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES public.companies(id),"
echo "ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;"
echo ""
echo "-- Atualizar vídeos existentes"
echo "UPDATE public.videos"
echo "SET created_by_type = 'system',"
echo "    display_order = CASE"
echo "        WHEN title ILIKE '%introdução%' THEN 1"
echo "        WHEN title ILIKE '%básico%' THEN 2"
echo "        WHEN title ILIKE '%avançado%' THEN 10"
echo "        ELSE 5"
echo "    END"
echo "WHERE created_by_type IS NULL;"
echo ""
echo "-- Criar índices"
echo "CREATE INDEX IF NOT EXISTS idx_videos_created_by_type ON public.videos(created_by_type);"
echo "CREATE INDEX IF NOT EXISTS idx_videos_manager_id ON public.videos(manager_id);"
echo "CREATE INDEX IF NOT EXISTS idx_videos_company_id ON public.videos(company_id);"
echo "================================================"
echo ""
echo "✅ Após executar o SQL, teste novamente o upload de vídeos"
echo ""
echo "🧪 Para testar: Cole scripts/test-video-upload.js no Console do navegador"